const SET_LOC_CITY = 'SET_LOC_CITY';
const SET_LOC_CITY_PLACE_ID = 'SET_LOC_CITY_PLACE_ID';
const SET_LOC_BOUNDS = 'SET_LOC_BOUNDS';
const SET_LOC_LAT_LNG = 'SET_LOC_LAT_LNG';

export default {
    SET_LOC_CITY,
    SET_LOC_CITY_PLACE_ID,
    SET_LOC_BOUNDS,
    SET_LOC_LAT_LNG
};